namespace SpriteKind {
    export const helper = SpriteKind.create()
}
info.onScore(100, function () {
	
})
scene.onHitWall(SpriteKind.Enemy, function (sprite, location) {
	
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    info.player2.changeLifeBy(-1)
})
mp.onLifeZero(function (player2) {
	
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
})
music.play(music.createSoundEffect(WaveShape.Sine, 3384, 0, 83, 0, 500, SoundExpressionEffect.None, InterpolationCurve.Linear), music.PlaybackMode.InBackground)
info.setLife(5)
effects.clouds.startScreenEffect()
scene.setBackgroundColor(9)
mp.setPlayerSprite(mp.playerSelector(mp.PlayerNumber.Three), sprites.create(img`
    .......ff...............
    ....ffff2ff.............
    ..ffeeeef2ff............
    .ffeeeeef22ff...........
    .feeeeffeeeef...........
    .fffffee2222ef..........
    fffe222ffffe2f..........
    ffffffffeeefff..........
    fefe44edf44eef..........
    .fee4d41fddef...........
    ..feee4dddee.c..........
    ...f2222eeddeccccccc....
    ...f444e44ddecddddd.....
    ...fffffeeee.ccccc......
    ..ffffffff...c..........
    ..fff..ff...............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy))
mp.setPlayerSprite(mp.playerSelector(mp.PlayerNumber.Four), sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .....fffc111d111f.......
    ...fc111cdd11d111f......
    ...f1b1b1bf11fbddf......
    ...fbfbffbf11fbddf......
    ......fcf111111bbf......
    .......ccbdb1b1fcf......
    .......fffbfbfdff.......
    ........ffffffff........
    ........fffffffffff.....
    .........fffffc111cf....
    .........fffff1b1b1f....
    ..........ffffbfbfbf....
    ...........ffff.........
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy))
mp.setPlayerSprite(mp.playerSelector(mp.PlayerNumber.Two), sprites.create(img`
    . . . . c c c c c . . . . . . . 
    . . c c 2 2 f f 2 c . . . . . . 
    . c 2 2 2 2 4 4 f 2 c . . . . . 
    c 2 2 2 2 2 1 4 f 2 2 c . . . . 
    c 2 2 2 2 2 4 4 f 2 2 2 c . . . 
    c c b b 1 b 2 2 2 2 2 2 c . . . 
    c 2 3 3 3 2 2 2 2 2 2 2 4 c . . 
    c 2 2 2 2 2 2 2 2 2 4 4 4 c . . 
    . c 2 2 2 2 b 2 2 2 4 4 4 c . . 
    f . c b b c 2 2 b 4 4 4 4 c . . 
    4 f f f f 2 2 b b f f 4 4 c c c 
    4 4 2 2 2 f f f f 2 2 f f 4 4 c 
    f 4 2 4 2 2 2 2 2 2 2 2 4 f f c 
    f 4 4 4 f 2 2 2 f 2 f 2 2 2 4 4 
    4 4 4 4 4 2 2 2 2 2 4 4 4 4 4 4 
    f f 4 4 4 4 4 4 4 4 4 4 4 4 4 f 
    `, SpriteKind.helper))
mp.setPlayerSprite(mp.playerSelector(mp.PlayerNumber.Two), sprites.create(img`
    . . . . . . . b 6 6 6 c b c b c 
    . . . . c c c c b 6 6 6 c 9 9 d 
    . . c c 9 9 9 9 c c 6 6 c 9 9 b 
    . c 9 9 9 9 9 9 9 9 c c 9 9 9 c 
    c 9 9 9 9 9 1 f 9 9 9 c 9 9 9 c 
    c 9 9 9 9 9 f f 9 9 9 9 9 9 9 b 
    c 9 9 9 9 9 9 9 9 9 9 9 9 9 9 c 
    c c b b 1 b 9 9 9 9 9 9 6 c c . 
    c 9 3 3 3 9 9 9 9 9 6 6 6 c . . 
    . b 9 9 9 9 9 9 9 9 6 6 6 c . . 
    . . c b b c 9 9 1 6 6 6 6 c . . 
    . c b b c 9 9 b b 6 6 6 6 c c c 
    . c c c c c c c 6 6 6 6 6 6 6 c 
    . . . c c c c c 9 9 b 6 6 6 c . 
    . . c b b c c c 9 9 b c c . . . 
    . . c c c c c d 9 9 c . . . . . 
    `, SpriteKind.Player))
mp.moveWithButtons(mp.playerSelector(mp.PlayerNumber.One))
mp.moveWithButtons(mp.playerSelector(mp.PlayerNumber.Two))
mp.moveWithButtons(mp.playerSelector(mp.PlayerNumber.Four))
mp.moveWithButtons(mp.playerSelector(mp.PlayerNumber.Three))
